# Generated by Django 5.0.6 on 2024-05-15 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=220)),
                ('client_location', models.CharField(max_length=1000)),
                ('job_title', models.CharField(max_length=220)),
                ('job_description', models.TextField(max_length=2000)),
                ('due_delivery_time', models.DateTimeField()),
                ('link', models.CharField(max_length=60, unique=True)),
                ('date_uploaded', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=60, unique=True)),
                ('date_uploaded', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonFlex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='video')),
                ('picture', models.ImageField(blank=True, upload_to='picture')),
                ('vibes', models.TextField(blank=True, max_length=400)),
                ('corper_name', models.CharField(blank=True, max_length=3096)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corper_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('hub_id', models.CharField(blank=True, max_length=200)),
                ('about_me', models.TextField(blank=True, max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
